spring:
  application:
    name: spring-security

  datasource:
    username: postgres
    password: postgres@123
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://68.183.187.158:5432/oauth-db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true