
server:
  port: 8081

spring:
  application:
    name: client-server

  datasource:
    username: postgres
    password: postgres@123
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://68.183.187.158:5432/oauth-db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  security:
    oauth2:
      client:
        registration:
          api-client-oidc:
            client-id: api-client
            client-secret: ""
            scope: openid,profile,api.read
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: API Client OIDC
            provider: custom-provider

        provider:
          custom-provider:
            authorization-uri: http://127.0.0.1:8080/oauth2/authorize
            token-uri: http://127.0.0.1:8080/oauth2/token
            user-info-uri: http://127.0.0.1:8080/userinfo
            jwk-set-uri: http://127.0.0.1:8080/oauth2/jwks
            user-name-attribute: sub

logging:
  level:
    org:
      springframework:
        security: debug
        web: debug
